name: Deploy to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Add EC2 SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2.pem
        chmod 600 ~/.ssh/ec2.pem
    
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose-plugin
    
    - name: Build and push Docker images
      run: |
        docker compose -f docker-compose.yml build
        docker save -o frontend.tar frontend
        docker save -o api.tar api
    
    - name: Transfer files to EC2
      run: |
        scp -i ~/.ssh/ec2.pem -o StrictHostKeyChecking=no \
          docker-compose.yml \
          frontend.tar \
          api.tar \
          .env.docker \
          ubuntu@${{ secrets.EC2_HOST }}:~/app/
    
    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/ec2.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} '
          cd ~/app
          docker load -i frontend.tar
          docker load -i api.tar
          cp .env.docker .env
          docker compose down
          docker compose up -d
          rm frontend.tar api.tar
        '